[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "bids-manager"
version = "0.1.0"
description = "GUI application to manage BIDS datasets"
readme = "README.md"
license = {text = "MIT"}
authors = [{name="BIDS Manager"}]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "pydicom",
    "pandas",
    "PyQt5",
    "PyQtWebEngine",
    "heudiconv @ git+https://github.com/karellopez/heudiconv",
    "nipype @ git+https://github.com/karellopez/nipype",
    "dcm2niix",
    "nibabel",
    "numpy",
    "psutil",
    "matplotlib",
    "joblib==1.4.2",
]


[project.scripts]
bids-manager = "bids_manager.gui:main"
dicom-inventory = "bids_manager.dicom_inventory:main"
build-heuristic = "bids_manager.build_heuristic_from_tsv:main"
run-heudiconv = "bids_manager.run_heudiconv_from_heuristic:main"
post-conv-renamer = "bids_manager.post_conv_renamer:main"
fill-bids-ignore = "bids_manager.fill_bids_ignore:main"


[tool.setuptools]
packages = ["bids_manager"]
include-package-data = true

[tool.setuptools.package-data]
"bids_manager" = [
    "miscellaneous/images/Logo.png",
    "miscellaneous/images/Icon.png",
    "miscellaneous/images/ANCP_lab.png",
    "miscellaneous/images/Karel.jpeg",
    "miscellaneous/images/Jochem.jpg",
]

